### ISSUE TITLE
Compatibility with Tasks plugin (feature request)

### ISSUE THREAD

**Issue by coneos** [wenlzhang/obsidian-todoist-context-bridge#4]
Great plugin! Unfortunately I am not sure I can use it as it is because it is not compatible with Tasks which I use in Kanban boards, you are using a different syntax for parameters.
That would be amazing to detect Tasks parameters (due date, priority etc..) and inserting them into your modal before syncing with Todoist

**Comment by wenlzhang** [comment]
Now I added the Tasks plugin support. Due date, Priority and Cleanup Patterns are supported. Welcome to test and give feedback:
https://github.com/wenlzhang/obsidian-todoist-context-bridge/releases/tag/0.10.0

**Comment by wenlzhang** [comment]
Closing this issue for now. Please reopen it if anything else is needed.
